### ISSUE TITLE
Link to tock app is incorrect

### ISSUE THREAD

**Issue by jessieay** [18F/angrytock#11]
Just received a message from angrytock -- it is linking to the wrong place.

<img width="460" alt="screen shot 2015-12-15 at 9 15 05 am" src="https://cloud.githubusercontent.com/assets/601515/11817923/21cdf106-a30c-11e5-8f73-d2fada652e4e.png">

(should be linking to https://tock.18f.gov/ -- link above gives a 403)

**Comment by geramirez** [comment]
This should be resolved
